// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestMVCInPractice.Models;

public partial class MultiLangauge
{
    public int id { get; set; }

    public string ArmenianLang { get; set; }

    public string RussioanLang { get; set; }

    public string EnglishLang { get; set; }
}