// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Codenyx.Models;

public partial class LanguagesContext : DbContext
{
    internal readonly object MultiLanguage;

    public LanguagesContext(DbContextOptions<LanguagesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MultiLanguage> MultiLanguages { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MultiLanguage>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__MultiLan__3213E83F6DA47518");

            entity.ToTable("MultiLanguage");

            entity.Property(e => e.ArmenianLang).UseCollation("Latin1_General_100_CI_AS_SC_UTF8");
            entity.Property(e => e.EnglishLang).UseCollation("Latin1_General_100_CI_AS_SC_UTF8");
            entity.Property(e => e.RussianLang).UseCollation("Latin1_General_100_CI_AS_SC_UTF8");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}