// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Codenyx.Models;

public partial class MultiLanguage
{
    public int id { get; set; }

    public string ArmenianLang { get; set; }

    public string RussianLang { get; set; }

    public string EnglishLang { get; set; }
}